### ISSUE TITLE
Upgrade blueprint

### ISSUE THREAD

**Issue by flaviocopes** [DarrylDias/Sidewalk#3]
Hi DarrylDias to make the theme work fine in Grav Admin, you can update the blueprint to allow changing the theme options from the admin side. See https://github.com/getgrav/grav-theme-photographer/commit/89015918c3f358d057d95a4e1744f1083259a3b5 as an example :)

**Comment by DarrylDias** [comment]
Thanks for opening this issue, I will work on that, in the next release.
