### ISSUE TITLE
Thumbnail not shown in Admin

### ISSUE THREAD

**Issue by flaviocopes** [DarrylDias/Sidewalk#4]
Needs to be a jpg not a png.

**Comment by DarrylDias** [comment]
I will work on this issue when I have free time, 

@flaviocopes thank you for opening this issue :+1:.

**Comment by simonhermann** [comment]
currently it does not show in Admin at all. Can be fixed by renaming Sidewalk.yaml to start with lowercase s.

**Comment by DarrylDias** [comment]
@simonhermann Thank you for letting me know how to fix it, It has been fixed. 👍
