### ISSUE TITLE
compatible with Grav v1.1.1 - Admin v1.1.2 ?

### ISSUE THREAD

**Issue by andrekutianski** [DarrylDias/Sidewalk#5]
this theme do not install in Grav v1.1.1 - Admin v1.1.2

**Comment by DarrylDias** [comment]
@andrebellafronte I will be looking into this issue and soon patch this bug, thank you for opening this issue.

**Comment by DarrylDias** [comment]
The theme has finally been updated to work with Grav v1.7.13 and above.
